import type { StrategyRules } from "@/lib/strategies/types";

export const defaultStrategyRules: StrategyRules = {
  markets: ["Forex", "Gold"],
  symbols: ["XAUUSD", "EURUSD"],
  sessions: ["London", "New York"],
  directionBias: "both",
  requiresBos: true,
  requiresChoch: false,
  requiresLiquiditySweep: true,
  requiresFvg: true,
  requiresOrderBlock: false,
  minimumRr: 2,
  maxRiskPercent: 1,
  avoidHighImpactNews: true,
  newsBufferMinutes: 60,
  entryModel: "liquidity-sweep-confirmation",
  stopLossModel: "swing-high-low",
  takeProfitModel: "next-liquidity",
};

export const defaultStrategyTemplates = [
  {
    name: "ICT London Kill Zone",
    description: "Liquidity sweep and BOS confirmation during London volatility expansion.",
    rules: {
      ...defaultStrategyRules,
      markets: ["Forex", "Gold"],
      symbols: ["XAUUSD", "EURUSD"],
      sessions: ["London"],
      directionBias: "both",
      requiresBos: true,
      requiresLiquiditySweep: true,
      requiresFvg: true,
      minimumRr: 2,
      maxRiskPercent: 1,
      entryModel: "liquidity-sweep-confirmation",
    } satisfies StrategyRules,
  },
  {
    name: "BOS + FVG Continuation",
    description: "Trend continuation playbook after break of structure and fair value gap retest.",
    rules: {
      ...defaultStrategyRules,
      markets: ["Forex", "Indices"],
      symbols: ["EURUSD", "NAS100", "US30"],
      sessions: ["London", "New York"],
      directionBias: "trend-following",
      requiresBos: true,
      requiresLiquiditySweep: false,
      requiresFvg: true,
      requiresOrderBlock: false,
      minimumRr: 2.5,
      entryModel: "fvg-retest",
      takeProfitModel: "fixed-rr",
    } satisfies StrategyRules,
  },
  {
    name: "Liquidity Sweep Reversal",
    description: "Reversal model after stop run, displacement, and confirmation entry.",
    rules: {
      ...defaultStrategyRules,
      markets: ["Gold", "Crypto", "Indices"],
      symbols: ["XAUUSD", "BTCUSDT", "NAS100"],
      sessions: ["New York"],
      directionBias: "reversal",
      requiresBos: false,
      requiresChoch: true,
      requiresLiquiditySweep: true,
      requiresFvg: false,
      requiresOrderBlock: true,
      minimumRr: 3,
      maxRiskPercent: 0.75,
      entryModel: "order-block-retest",
      stopLossModel: "order-block-invalid",
    } satisfies StrategyRules,
  },
];
