-- Stage 22 - Market Intelligence Foundation
-- Provider data is written only by trusted server code. Authenticated users
-- can read verified candles and derived snapshots, but cannot mutate them.

create table if not exists public.market_candles (
  id bigint generated by default as identity primary key,
  provider text not null,
  symbol text not null,
  timeframe text not null check (timeframe in ('5m', '15m', '1h', '4h', '1D')),
  opened_at timestamptz not null,
  open numeric not null,
  high numeric not null,
  low numeric not null,
  close numeric not null,
  volume numeric,
  is_closed boolean not null default true,
  fetched_at timestamptz not null default now(),
  constraint market_candles_valid_ohlc check (
    high >= low
    and high >= open
    and high >= close
    and low <= open
    and low <= close
  )
);

create table if not exists public.market_snapshots (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  symbol text not null,
  market_type text not null,
  timeframe text not null check (timeframe in ('5m', '15m', '1h', '4h', '1D')),
  last_price numeric not null,
  change_percent numeric,
  bias text not null check (bias in ('bullish', 'bearish', 'neutral')),
  structure_state text not null check (structure_state in ('trending', 'ranging', 'reversal', 'unclear')),
  bos_detected boolean not null default false,
  choch_detected boolean not null default false,
  liquidity_sweep_detected boolean not null default false,
  fvg_detected boolean not null default false,
  order_block_detected boolean not null default false,
  premium_discount_state text not null check (premium_discount_state in ('premium', 'discount', 'equilibrium', 'unknown')),
  setup_readiness text not null check (setup_readiness in ('no-setup', 'watching', 'forming', 'ready')),
  confidence numeric not null check (confidence >= 0 and confidence <= 100),
  candle_count integer not null default 0 check (candle_count >= 0),
  summary text not null,
  key_levels jsonb not null default '[]'::jsonb,
  warnings text[] not null default '{}',
  source_time timestamptz not null,
  fetched_at timestamptz not null default now(),
  analysis_version text not null default 'market-intelligence-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_data_sync_runs (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid references auth.users(id) on delete set null,
  provider text not null,
  symbol text not null,
  timeframe text not null,
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  fetched_count integer not null default 0 check (fetched_count >= 0),
  upserted_count integer not null default 0 check (upserted_count >= 0),
  error_code text,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists market_candles_provider_symbol_timeframe_opened_idx
  on public.market_candles (provider, symbol, timeframe, opened_at);
create index if not exists market_candles_symbol_timeframe_opened_idx
  on public.market_candles (symbol, timeframe, opened_at desc);
create unique index if not exists market_snapshots_provider_symbol_timeframe_idx
  on public.market_snapshots (provider, symbol, timeframe);
create index if not exists market_snapshots_timeframe_fetched_idx
  on public.market_snapshots (timeframe, fetched_at desc);
create index if not exists market_data_sync_runs_requested_by_created_idx
  on public.market_data_sync_runs (requested_by, created_at desc);
create index if not exists market_data_sync_runs_status_created_idx
  on public.market_data_sync_runs (status, created_at desc);

drop trigger if exists set_market_snapshots_updated_at on public.market_snapshots;
create trigger set_market_snapshots_updated_at
  before update on public.market_snapshots
  for each row execute function public.set_updated_at();

alter table public.market_candles enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.market_data_sync_runs enable row level security;

drop policy if exists "Authenticated users can read market candles" on public.market_candles;
create policy "Authenticated users can read market candles"
  on public.market_candles for select to authenticated using (true);

drop policy if exists "Authenticated users can read market snapshots" on public.market_snapshots;
create policy "Authenticated users can read market snapshots"
  on public.market_snapshots for select to authenticated using (true);

drop policy if exists "Users can read own market sync runs" on public.market_data_sync_runs;
create policy "Users can read own market sync runs"
  on public.market_data_sync_runs for select to authenticated
  using ((select auth.uid()) = requested_by);

revoke all on table public.market_candles from anon, authenticated;
revoke all on table public.market_snapshots from anon, authenticated;
revoke all on table public.market_data_sync_runs from anon, authenticated;
grant select on table public.market_candles to authenticated;
grant select on table public.market_snapshots to authenticated;
grant select on table public.market_data_sync_runs to authenticated;
grant all on table public.market_candles to service_role;
grant all on table public.market_snapshots to service_role;
grant all on table public.market_data_sync_runs to service_role;
grant usage, select on sequence public.market_candles_id_seq to service_role;
