import { Bot, CheckCircle2, CircleAlert, Gauge, Sparkles } from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";
import { GenerateAIReviewButton } from "@/components/journal/GenerateAIReviewButton";
import type { AITradeReview } from "@/lib/trading/types";

interface AIReviewCardProps {
  review: AITradeReview | null;
  tradeId: string;
}

function scoreValue(value: number | null) {
  return Math.round(Number(value) || 0);
}

function sourceLabel(review: AITradeReview) {
  return review.generation_source === "ai" ? "Generated by AI" : "Generated by local rules";
}

function hasNewsContext(review: AITradeReview) {
  const text = [...(review.strengths ?? []), ...(review.weaknesses ?? []), ...(review.recommendations ?? []), review.summary ?? ""].join(" ").toLowerCase();
  return text.includes("economic event") || text.includes("news window") || text.includes("news risk");
}

function ScorePill({ label, value }: { label: string; value: number | null }) {
  const score = scoreValue(value);

  return (
    <div className="rounded-xl border border-white/10 bg-black/20 p-3">
      <div className="text-xs text-zinc-500">{label}</div>
      <div className="mt-2 flex items-center justify-between gap-3">
        <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/10">
          <div className="h-full rounded-full bg-white/80" style={{ width: `${score}%` }} />
        </div>
        <span className="text-sm font-semibold text-white">{score}</span>
      </div>
    </div>
  );
}

function ReviewList({ title, items, icon }: { title: string; items: string[] | null; icon: "positive" | "negative" | "neutral" }) {
  const Icon = icon === "positive" ? CheckCircle2 : icon === "negative" ? CircleAlert : Sparkles;
  const iconClass = icon === "positive" ? "text-emerald-300" : icon === "negative" ? "text-rose-300" : "text-zinc-300";

  return (
    <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
      <h3 className="flex items-center gap-2 text-sm font-semibold">
        <Icon className={`h-4 w-4 ${iconClass}`} />
        {title}
      </h3>
      <div className="mt-3 space-y-2 text-sm leading-6 text-zinc-400">
        {(items?.length ? items : ["No items generated yet."]).map((item) => (
          <p key={item}>{item}</p>
        ))}
      </div>
    </div>
  );
}

export function AIReviewCard({ review, tradeId }: AIReviewCardProps) {
  if (!review) {
    return (
      <GlassCard className="p-4 md:p-6">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-start gap-3">
            <div className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[0.06]">
              <Bot className="h-5 w-5 text-zinc-300" />
            </div>
            <div>
              <h2 className="text-base font-semibold">AI Trade Review</h2>
              <p className="mt-1 max-w-2xl text-sm leading-6 text-zinc-400">
                Generate a structured review based on your trade data, risk, notes, and Smart Money/ICT checklist.
              </p>
            </div>
          </div>
          <GenerateAIReviewButton tradeId={tradeId} label="Generate AI Review" />
        </div>
      </GlassCard>
    );
  }

  const totalScore = scoreValue(review.total_score);

  return (
    <GlassCard className="p-4 md:p-6">
      <div className="flex flex-col gap-6 xl:flex-row xl:items-start xl:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-3">
            <div className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[0.06]">
              <Bot className="h-5 w-5 text-zinc-300" />
            </div>
          <div>
            <h2 className="text-base font-semibold">AI Trade Review</h2>
              <p className="mt-1 text-sm text-zinc-500">{sourceLabel(review)}{review.model ? ` · ${review.model}` : ""}</p>
              <p className="mt-1 text-xs text-zinc-500">{hasNewsContext(review) ? "News context included" : "No news context detected"}</p>
            </div>
          </div>
          <p className="mt-5 max-w-3xl text-sm leading-6 text-zinc-300">{review.summary}</p>
        </div>

        <div className="flex shrink-0 items-center gap-5">
          <div className="grid h-24 w-24 place-items-center rounded-full border-[9px] border-white/15 border-t-white bg-black/25">
            <div className="text-center">
              <div className="text-3xl font-semibold text-white">{totalScore}</div>
              <div className="text-xs text-zinc-500">/100</div>
            </div>
          </div>
          <GenerateAIReviewButton tradeId={tradeId} label="Regenerate Review" />
        </div>
      </div>

      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        <ScorePill label="Structure" value={review.structure_score} />
        <ScorePill label="Liquidity" value={review.liquidity_score} />
        <ScorePill label="ICT" value={review.ict_score} />
        <ScorePill label="Risk" value={review.risk_score} />
        <ScorePill label="News" value={review.news_score} />
        <ScorePill label="Psychology" value={review.psychology_score} />
      </div>

      <div className="mt-4 grid gap-4 xl:grid-cols-3">
        <ReviewList title="Strengths" items={review.strengths} icon="positive" />
        <ReviewList title="Weaknesses" items={review.weaknesses} icon="negative" />
        <ReviewList title="Recommendations" items={review.recommendations} icon="neutral" />
      </div>

      <div className="mt-4 flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-zinc-500">
        <Gauge className="h-4 w-4" />
        {review.generation_source === "ai" ? "This review was generated with the configured AI provider and validated before saving." : "This review uses the local rules engine fallback."}
      </div>
    </GlassCard>
  );
}
